# @package _global_

defaults:
  - /global: default
  - /pipeline: anonymization
  - /anonymizer: emotion_compensation
  - /dataset: stutter
  - _self_

target_id: ""

anonymizer:
  feature_providers:
    - _target_: quick_convert.components.feature_providers.sidecar.PatternSidecarFeatureProvider
      key: speaker_embedding
      root: /cfs/home/u036742/emotion-compensation/results/IEMOCAP_dev_ohnn_pre_esd_msp_sad1
      pattern: "{stem}_{step}.xvector"
      step: 1
    - _target_: quick_convert.components.feature_providers.online.OnlineFeatureProvider
      extractor:
        _target_: quick_convert.components.donors.emotion_compensation.f0.PYAAPTF0Extractor

dataset:
  load: true
  target_sr: 16000
  # limit to sentences, because original emotion-compensation does that
