# @package _global_

defaults:
  - /global: default
  - /pipeline: precompute_features
  - /dataset: stutter
  - _self_

feature_extractor:
  _target_: quick_convert.components.feature_extractors.f0.F0Extractor
  extract_fn: quick_convert.components.donors.emotion_compensation.utils.get_yaapt_f0

dataset:
  load: true
  target_sr: 16000

pipeline:
  dataset: ${dataset}
  extractor: ${feature_extractor}
  out_root: ${out_root}/precomputed/${hydra:runtime.choices.dataset}/f0_yaapt
