hparams_file: quick_convert/pipelines/asv/hyperparams/train_ecapa_tdnn.yaml
eval_hparams_file: quick_convert/pipelines/asv/hyperparams/verification_ecapa.yaml

exp_name: ${asv_name}_${dataset_name}${suffix}
exp_folder: ${output_base_folder}/${asv.exp_name}

prepared_data_path: ${asv.exp_folder}/data
overwrite_csv: false

prep:
    save_folder: ${asv.exp_folder}/data # cross check if it should match with prepared_data_path; this is where train/dev CSVs are written
    train_fraction: 0.9
    # train_splits: ${dataset.splits}
    # dev_splits: []
    randomize_within_split: false
    seed: 1337

overrides:
    output_folder: ${asv.exp_folder}
    save_folder: ${asv.exp_folder}
    data_folder: /unused/by_custom_prep
    skip_prep: true
    
