_target_: quick_convert.data.base_dataset.BaseDataset
root: /cfs/projects/funded/privadia/data/IEMOCAP_full_release
splits:
  - Session1
  - Session2
  - Session3
  - Session4
  - Session5
exclude_patterns:
  - ._*.wav
